import { ChakraProvider } from "@chakra-ui/react";
import { StoreProvider } from "@/stores/storeProvider";

export const metadata = {
	title: "ParcelAdmin",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<ChakraProvider>{children}</ChakraProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
